spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: abcd1234
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.Oracle21cDialect

redis:
  host: localhost
  port: 6379

redisStatus:
  active: false

server:
  port : 8081