spring:
  datasource:
    url: jdbc:h2:mem:default
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

redis:
  host: localhost
  port: 6379

redisStatus:
  active: false